# Dataloader

### Imports

In [22]:
# -- public imports

import os
import pandas as pd

In [23]:
# -- private import

In [42]:
# -- dev imports

from python_files.data import ArgumentMiningDataset
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


### Load the data

In [31]:
base_path = '../../data/UCL/dataset2'
dataset_path = os.path.join(base_path, 'df_labels_general.json')

label_map_path = os.path.join(base_path, 'df_label_map_bio.json')
df_label_map_bio = pd.read_json(label_map_path)

label_map_path = os.path.join(base_path, 'df_label_map_bieo.json')
df_label_map_bieo = pd.read_json(label_map_path)

label_map_path = os.path.join(base_path, 'df_label_map_bixo.json')
df_label_map_bixo = pd.read_json(label_map_path)

df = pd.read_json(dataset_path)
df.head()

label_type       label                                               text  \
0          O       Other  Should students be taught to compete or to coo...   
1         T1  MajorClaim  we should attach more importance to cooperatio...   
2          O       Other                                  .\nFirst of all,    
3         T3       Claim  through cooperation, children can learn about ...   
4          O       Other                                                 .    

   span_start  span_end    doc_id  \
0           0       503  essay001   
1         503       575  essay001   
2         575       591  essay001   
3         591       714  essay001   
4         714       716  essay001   

                                    predictionString  \
0  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...   
1           [83, 84, 85, 86, 87, 88, 89, 90, 91, 92]   
2                                   [93, 94, 95, 96]   
3  [97, 98, 99, 100, 101, 102, 103, 104, 105, 106...   
4                                              [115]   

                                           label_bio  \
0  [O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...   
1  [B-MajorClaim, I-MajorClaim, I-MajorClaim, I-M...   
2                                       [O, O, O, O]   
3  [B-Claim, I-Claim, I-Claim, I-Claim, I-Claim, ...   
4                                                [O]   

                                          label_bieo  
0  [O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...  
1  [B-MajorClaim, I-MajorClaim, I-MajorClaim, I-M...  
2                                       [O, O, O, O]  
3  [B-Claim, I-Claim, I-Claim, I-Claim, I-Claim, ...  
4                                                [O]

### Develop Dataset

In [32]:
df_text = df[['text', 'label_bio']].rename(columns={'label_bio':'labels'})
df_text

text  \
0      Should students be taught to compete or to coo...   
1      we should attach more importance to cooperatio...   
2                                      .\nFirst of all,    
3      through cooperation, children can learn about ...   
4                                                     .    
...                                                  ...   
12575                                       . Secondly,    
12576  playing sport makes children getting healthy a...   
12577                                . \nIn conclusion,    
12578  both studying hard at school and playing sport...   
12579                                                  .   

                                                  labels  
0      [O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...  
1      [B-MajorClaim, I-MajorClaim, I-MajorClaim, I-M...  
2                                           [O, O, O, O]  
3      [B-Claim, I-Claim, I-Claim, I-Claim, I-Claim, ...  
4                                                    [O]  
...                                                  ...  
12575                                             [O, O]  
12576  [B-Premise, I-Premise, I-Premise, I-Premise, I...  
12577                                          [O, O, O]  
12578  [B-MajorClaim, I-MajorClaim, I-MajorClaim, I-M...  
12579                                                [O]  

[12580 rows x 2 columns]

In [45]:
df_label_map_bio

label_id         label
0         0             O
1         1  B-MajorClaim
2         2  I-MajorClaim
3         3       B-Claim
4         4       I-Claim
5         5     B-Premise
6         6     I-Premise

In [55]:
dataset = ArgumentMiningDataset(df_label_map_bio, df_text, strategy='bio', tokenizer=0, max_length=0)

[list([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
 list([1, 2, 2, 2, 2, 2, 2, 2, 2, 2]) list([0, 0, 0, 0]) ...
 list([0, 0, 0]) list([1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]) list([0])]


In [51]:
print(df_label_map_bio.label)

0               O
1    B-MajorClaim
2    I-MajorClaim
3         B-Claim
4         I-Claim
5       B-Premise
6       I-Premise
Name: label, dtype: object


In [61]:
pd.DataFrame(data={'a':[1,2,3]}).loc[0]

a    1
Name: 0, dtype: int64

In [64]:
import torch
x = torch.tensor([0,0,0,0,1,2,2,2,2,3,4,4,4,])
unique, inverse = torch.unique(x, sorted=True, return_inverse=True)
perm = torch.arange(inverse.size(0), dtype=inverse.dtype, device=inverse.device)
inverse, perm = inverse.flip([0]), perm.flip([0])
perm = inverse.new_empty(unique.size(0)).scatter_(0, inverse, perm)
perm

tensor([ 0,  4,  5,  9, 10])

In [163]:
words = 'Another sentence. NLP is the coolest Learning. According to research. I like NLP'
targets = [0, 0, 1, 2, 2, 2, 2, 3, 4, 4, 0, 0, 0]
actual_targets = [0, 0, 0, 0, 1, 2, 2, 2, -1, 2, -1, 3, -1, 4, 4, -1, 0, 0, 0]
targets = torch.as_tensor(targets, dtype=torch.long)
word_ids = [0, 0, 1, 1, 2, 3, 4, 5, 5, 6, 6, 7, 7, 8, 9, 9, 10, 11, 12]
word_id_mask = [True] * len(word_ids)

targets_end = torch.tensor([
    0, 0, 1, 2, 2, 2, 3, 4, 5, 6, 0, 0, 0
])
actual_targets_end =[0, 0, 0, 0, 1, 2, 2, 2, -1, -1, 3, 4, -1, 5, 6, -1, 0, 0, 0]

In [143]:
def _first_appearance_of_unique_item(x):
    unique, inverse = torch.unique(x, sorted=True, return_inverse=True)
    perm = torch.arange(inverse.size(0), dtype=inverse.dtype, device=inverse.device)
    inverse, perm = inverse.flip([0]), perm.flip([0])
    perm = inverse.new_empty(unique.size(0)).scatter_(0, inverse, perm)
    return perm

In [160]:
def _label_standard(targets, word_id_mask, word_ids):
    max_length = len(word_ids)
    
    expanded_targets = torch.zeros(max_length, dtype=torch.long)
    expanded_targets[word_id_mask] = targets[word_ids]
    word_start_ids = _first_appearance_of_unique_item(torch.as_tensor(word_ids))
    unique_word_ids, word_id_counts = torch.unique(torch.as_tensor(word_ids), return_counts=True)
    
    # here define the start and end labels
    end = True
    for i, (word_start_id, word_id, word_id_count) in enumerate(zip(word_start_ids, unique_word_ids, word_id_counts)):
        curr_target = expanded_targets[word_start_id]
        if curr_target: # step to filter the orhers
            if word_id_count > 1:
                ids = list(range(word_start_id, word_start_id+word_id_count))
                
                # TODO can make robust by adding string condition 'E-'
                if end and curr_target % 3 == 0: # TODO condition needs to change to read end from the strateg 
                    ids = ids[:-1]
                else:
                    ids = ids[1:]
                
                expanded_targets[ids] = -1 # this label needs to be changed!
            # need to have case bie
            # need to have case bio
            # need to have case bix
    print(expanded_targets)

In [161]:
_label_standard(targets_end, word_id_mask, word_ids)

tensor(3) tensor(4)
tensor(6) tensor(0)
tensor([ 0,  0,  0,  0,  1,  2,  2,  2, -1, -1,  3,  4, -1,  5, -1,  6,  0,  0,
         0])


In [154]:
actual_targets_end =[0, 0, 0, 0, 1, 2, 2, 2, -1, -1, 3, 4, -1, 5, -1, 6, 0, 0, 0]


In [168]:
torch.tensor([1])

tensor([1])